-- Migration to fix RLS violation on activity_logs table
-- Updates the activity log trigger to run as SECURITY DEFINER
-- and adds missing RLS policies for insertion.

-- 1. Update log_task_activity to be SECURITY DEFINER
-- This ensures the trigger can write activity logs regardless of the initiating user's RLS constraints.
CREATE OR REPLACE FUNCTION public.log_task_activity()
RETURNS TRIGGER AS $$
BEGIN
  -- Log status changes
  IF (TG_OP = 'UPDATE' AND OLD.status IS DISTINCT FROM NEW.status) THEN
    INSERT INTO public.activity_logs (task_id, user_id, action_type, old_value, new_value)
    VALUES (NEW.id, auth.uid(), 'status_changed', OLD.status, NEW.status);
  END IF;

  -- Log assignment changes
  IF (TG_OP = 'UPDATE' AND OLD.assigned_to IS DISTINCT FROM NEW.assigned_to) THEN
    INSERT INTO public.activity_logs (task_id, user_id, action_type, old_value, new_value)
    VALUES (NEW.id, auth.uid(), 'assigned', OLD.assigned_to::TEXT, NEW.assigned_to::TEXT);
  END IF;

  -- Log completion
  IF (TG_OP = 'UPDATE' AND OLD.status != 'completed' AND NEW.status = 'completed') THEN
    INSERT INTO public.activity_logs (task_id, user_id, action_type, new_value)
    VALUES (NEW.id, auth.uid(), 'completed', NEW.status);
  END IF;

  -- Log creation
  IF (TG_OP = 'INSERT') THEN
    INSERT INTO public.activity_logs (task_id, user_id, action_type, new_value)
    VALUES (NEW.id, auth.uid(), 'created', 'Task created');
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 2. Add MISSING INSERT policy for activity_logs
-- Allows logs to be generated by internal triggers and system actions.
DROP POLICY IF EXISTS "System can insert activity logs" ON public.activity_logs;
CREATE POLICY "System can insert activity logs" ON public.activity_logs
    FOR INSERT WITH CHECK (true);
